
services:
  backend:
    image: siddjuugi/rag-notebook-backend:latest
    container_name: rag-notebook-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@database:5432/rag_notebook
    networks:
      - rag-network
    depends_on:
      - database

  database:
    image: postgres:15-alpine
    container_name: rag-notebook-db
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rag_notebook
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local

# Usage:
# 1. Create a .env file with required environment variables
# 2. Run: docker-compose -f docker-compose.prod.yaml up -d
# 3. To stop: docker-compose -f docker-compose.prod.yaml down 


# docker-compose -f docker-compose.prod.yaml up -d
# docker-compose -f docker-compose.prod.yaml exec backend npx prisma migrate dev
